import test from 'node:test';
import assert from 'node:assert/strict';
import {todayLaPaz,availability,activePromotions,parseOptions,parseGallery,validatePromotions} from '../assets/catalog.js';
import {lines} from '../assets/core.js';
test('fecha boliviana cambia a medianoche local y no UTC',()=>{assert.equal(todayLaPaz(new Date('2026-10-02T03:59:59Z')),'2026-10-01');assert.equal(todayLaPaz(new Date('2026-10-02T04:00:00Z')),'2026-10-02');});
test('disponibilidad de fecha y estados impiden pedidos',()=>{assert.equal(availability({}).orderable,true);for(const estado_venta of ['agotado','encargo'])assert.equal(availability({estado_venta}).orderable,false);assert.equal(availability({estado_venta:'hoy',fecha_disponible:'2026-10-01'},'2026-10-01').orderable,true);assert.equal(availability({estado_venta:'hoy',fecha_disponible:'2026-10-01'},'2026-10-02').orderable,false);assert.deepEqual(lines({a:2},[{id:'a',precio:20,disponible:true,estado_venta:'agotado'}]),[]);});
test('promociones inclusivas, programadas, vencidas y desactivadas',()=>{const p={titulo:'Ejemplo',texto:'',inicio:'2026-10-01',fin:'2026-10-03',activo:true};for(const day of ['2026-10-01','2026-10-03'])assert.equal(activePromotions([p],day).length,1);for(const day of ['2026-09-30','2026-10-04'])assert.equal(activePromotions([p],day).length,0);assert.equal(activePromotions([{...p,activo:false}],'2026-10-02').length,0);assert.throws(()=>validatePromotions([{...p,fin:'2026-09-30'}]));});
test('opciones admiten precios claros y rechazan datos ambiguos',()=>{assert.deepEqual(parseOptions('Mediano | 24.50\nChocolate | 0'),[{nombre:'Mediano',precio:24.5},{nombre:'Chocolate',precio:0}]);for(const v of ['M|-1','M|3.141','M|Infinity','M|3|4','M|1\nm|2'])assert.throws(()=>parseOptions(v));assert.throws(()=>parseOptions(Array.from({length:13},(_,i)=>'O'+i+'|1').join('\n')));});
test('galería limita cantidad y rechaza protocolos inseguros',()=>{assert.deepEqual(parseGallery('https://example.com/a.jpg\nhttps://example.com/a.jpg'),['https://example.com/a.jpg']);assert.throws(()=>parseGallery('javascript:alert(1)'));assert.throws(()=>parseGallery(Array.from({length:6},(_,i)=>'https://example.com/'+i).join('\n')));});
