import {createRequire} from 'node:module';
import {readFile,writeFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
const root=new URL('../',import.meta.url);
const db=new PGlite();
await db.exec("create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$; grant usage on schema auth to anon,authenticated; grant execute on function auth.uid() to anon,authenticated;");
await db.exec(await readFile(new URL('sql/01-schema.sql',root),'utf8'));
await db.exec(await readFile(new URL('sql/02-demo.sql',root),'utf8'));
await db.exec(await readFile(new URL('sql/04-apariencia.sql',root),'utf8'));
await db.exec(await readFile(new URL('sql/04-apariencia.sql',root),'utf8'));
await db.exec(`create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id bigint generated always as identity,bucket_id text,name text);alter table storage.objects enable row level security;grant usage on schema storage to anon,authenticated;grant insert,select,update,delete on storage.objects to anon,authenticated;grant usage on sequence storage.objects_id_seq to anon,authenticated;`);
await db.exec(await readFile(new URL('sql/05-fotos-destacados.sql',root),'utf8'));
await db.exec(await readFile(new URL('sql/05-fotos-destacados.sql',root),'utf8'));
await db.exec(await readFile(new URL('sql/06-catalogo-diario.sql',root),'utf8'));
await db.exec(await readFile(new URL('sql/06-catalogo-diario.sql',root),'utf8'));
await db.exec(await readFile(new URL('sql/07-interaccion.sql',root),'utf8'));
await db.exec(await readFile(new URL('sql/07-interaccion.sql',root),'utf8'));
const a='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',b='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',s='cccccccc-cccc-4ccc-8ccc-cccccccccccc',rid='10000000-0000-4000-8000-000000000001',ridB='10000000-0000-4000-8000-000000000002',catB='20000000-0000-4000-8000-000000000099';
await db.exec(`insert into auth.users values ('${a}'),('${b}'),('${s}'); insert into public.restaurantes(id,nombre,slug,activo) values('${ridB}','Privado','privado',false); insert into public.categorias(id,restaurante_id,nombre) values('${catB}','${ridB}','Secreta'); insert into public.miembros values('${rid}','${a}'),('${ridB}','${b}'); insert into private.superadmins values('${s}');`);
async function role(name,uid=''){await db.exec("reset role;");await db.query("select set_config('request.jwt.claim.sub',$1,false)",[uid]);await db.exec('set role '+name);}
let checks=0;
async function blocked(sql){await assert.rejects(db.exec(sql));checks++;}
await role('anon');
await blocked(`insert into storage.objects(bucket_id,name) values('menu-productos','${rid}/aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa.webp')`);
assert.equal((await db.query('select * from public.restaurantes')).rows.length,1);checks++;
assert.equal((await db.query('select * from public.productos')).rows.length,6);checks++;
await blocked("insert into public.restaurantes(nombre,slug) values('Hack','hack')");
await blocked('select * from public.miembros');
await role('authenticated',a);
await db.exec(`insert into storage.objects(bucket_id,name) values('menu-productos','${rid}/aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa.webp')`);checks++;
await blocked(`insert into storage.objects(bucket_id,name) values('menu-productos','${ridB}/aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa.webp')`);
await blocked(`insert into storage.objects(bucket_id,name) values('menu-productos','${rid}/malicioso.svg')`);
await blocked(`update public.productos set destacado='viral' where restaurante_id='${rid}'`);
await blocked(`update public.restaurantes set movimiento='otro' where id='${rid}'`);
await blocked(`update public.restaurantes set estilo_tarjetas='otro' where id='${rid}'`);
assert.equal((await db.query(`update public.restaurantes set movimiento='suave' where id='${ridB}' returning id`)).rows.length,0);checks++;
await db.exec(`update public.restaurantes set plantilla='berries',modo_atencion='catalogo' where id='${rid}'`);checks++;
assert.equal((await db.query(`update public.restaurantes set plantilla='berries' where id='${ridB}' returning *`)).rows.length,0);checks++;
await blocked(`update public.restaurantes set color_principal='url(evil)' where id='${rid}'`);
await blocked(`update public.restaurantes set modo_atencion='delivery' where id='${rid}'`);
assert.equal((await db.query('select * from public.miembros')).rows.length,1);checks++;
await db.exec(`update public.productos set estado_venta='agotado',tamanos='[{"nombre":"Grande","precio":30}]',galeria='["https://example.com/foto.jpg"]' where restaurante_id='${rid}'`);checks++;
await blocked(`update public.productos set estado_venta='hoy',fecha_disponible=null where restaurante_id='${rid}'`);
await blocked(`update public.productos set extras='[{"nombre":"Extra","precio":-1}]' where restaurante_id='${rid}'`);
await blocked(`update public.productos set galeria='["javascript:alert(1)"]' where restaurante_id='${rid}'`);
await blocked(`update public.restaurantes set promociones='[{"titulo":"Oferta","texto":"","activo":true,"inicio":"2026-02-30","fin":"2026-03-01"}]' where id='${rid}'`);
await db.exec(`update public.restaurantes set promociones='[{"titulo":"Oferta","texto":"Consulta","activo":true,"inicio":"2026-10-01","fin":"2026-10-03"}]' where id='${rid}'`);checks++;
assert.equal((await db.query(`update public.restaurantes set promociones='[]' where id='${ridB}' returning id`)).rows.length,0);checks++;
assert.equal((await db.query(`update public.productos set estado_venta='agotado' where restaurante_id='${ridB}' returning id`)).rows.length,0);checks++;
await db.exec(`update public.productos set precio=29 where restaurante_id='${rid}'`);checks++;
await blocked(`insert into public.categorias(restaurante_id,nombre) values('${ridB}','Hack')`);
await blocked(`insert into public.productos(restaurante_id,categoria_id,nombre,precio) values('${rid}','${catB}','Hack',1)`);
await blocked(`update public.productos set restaurante_id='${ridB}' where restaurante_id='${rid}'`);
await blocked(`insert into public.miembros values('${ridB}','${a}')`);
await blocked(`insert into private.superadmins values('${a}')`);
assert.equal((await db.query(`update public.restaurantes set nombre='Hack' where id='${ridB}' returning *`)).rows.length,0);checks++;
await db.exec(`update public.categorias set activo=false where restaurante_id='${rid}'`);
await role('anon');assert.equal((await db.query('select * from public.productos')).rows.length,0);checks++;
await role('authenticated',b);assert.equal((await db.query(`select * from public.restaurantes where id='${ridB}'`)).rows.length,1);checks++;
await role('authenticated',s);assert.equal((await db.query('select public.soy_superadmin() as yes')).rows[0].yes,true);checks++;
await db.exec(`delete from public.miembros where usuario_id='${a}'`);
await role('authenticated',a);assert.equal((await db.query(`update public.productos set precio=1 where restaurante_id='${rid}' returning *`)).rows.length,0);checks++;
console.log('SQL / RLS checks passed:',checks);await db.close();

